### ISSUE TITLE
Consistently fails when mass converting batches of .wav files

### ISSUE THREAD

**Issue by Xenoslyce** [dfaust/soundkonverter#85] opened 2020-05-09 03:38 UTC
I keep trying to convert a lot of audio files to FLAC to save space, but it keeps giving me the exact same error on every other file. What's happening?

`Identifier: file:///home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A#_Min_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A%23_Min_Rhodes.wav
Log ID: 955735485
	Possible conversion strategies:
		wav ➝ flac (FLAC)
		wav ➝ flac (FFmpeg)
		wav ➝ flac (SoX)

Executing next step
Converting
	/usr/bin/flac -V --compression-level-8 "/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A" -o "/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/newnewnewflac"
	Progress: 0
	flac 1.3.2
	Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
	flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
	welcome to redistribute it under certain conditions.  Type `flac' for details.
	
	ERROR: can't open input file /home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A: No such file or directory
	Progress: 0
	Progress: 0
	Conversion failed. Exit code: 1
Converting
	/usr/bin/ffmpeg -i "/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A" -acodec flac "/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/newnewnewflac"
	Progress: 0
	Progress: 0
	ffmpeg version 4.1.3-0ppa1~18.04 Copyright (c) 2000-2019 the FFmpeg developers
	  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
	  configuration: --prefix=/usr --extra-version='0ppa1~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
	  libavutil      56. 22.100 / 56. 22.100
	  libavcodec     58. 35.100 / 58. 35.100
	  libavformat    58. 20.100 / 58. 20.100
	  libavdevice    58.  5.100 / 58.  5.100
	  libavfilter     7. 40.101 /  7. 40.101
	  libavresample   4.  0.  0 /  4.  0.  0
	  libswscale      5.  3.100 /  5.  3.100
	  libswresample   3.  3.100 /  3.  3.100
	  libpostproc    55.  3.100 / 55.  3.100
	/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A: No such file or directory
	Conversion failed. Exit code: 1
Converting
	/usr/bin/sox --no-glob "/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A" --compression 8 "/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/newnewnewflac"
	Progress: 0
	/usr/bin/sox FAIL formats: can't open input file `/home/Procyon/Samples/Unpacking/Cymatics_-_Oracle_Sample_Pack/Melodies/Loop_Stems/Cymatics_-_Oracle_Classic_Melody_Loop_5_-_88_BPM_A': No such file or directory
	Progress: 0
	Progress: 0
	Progress: 0
	Conversion failed. Exit code: 2
	No more backends left to try :(

Removing file from conversion list. Exit code 6 (An error occurred)
	Conversion time: 6s 364ms
	Output file size: 0 B
	File size ratio: nan %
Finished logging`

**Comment by Xenoslyce** [comment] 2020-05-09 03:42
Version 3.0.1.

**Comment by dfaust** [comment] 2020-05-09 06:27
Looks like the problem is caused by the "#" character (url encoded as "%23") in the file name.
Please try renaming the files.

**Comment by dfaust** [comment] 2020-05-09 06:28
Duplicate of #63

**Closed by dfaust** 2020-05-09 06:28 UTC
